### ISSUE TITLE
contains() or begins_with() don't work.

### ISSUE THREAD

**Issue by ohjisu** [passren/PyDynamoDB#24] opened 2023-02-15 09:00 UTC
1. contains() and begins_with() are not available in PartiQL [SELECT statements].

The syntax below is executable.
`SELECT * FROM UserTB WHERE user_name = 'tes0125' Limit 2`

contains() or begins_with() don't work. [SELECT statements]
`SELECT * FROM UserTB WHERE user_name = 'tes0125' AND begins_with(range_key, 'FRIEND#') Limit 2`

2. Is there any way to handle paging?

**Comment by passren** [comment] 2023-02-16 02:26
@ohjisu Thanks for your feedback.
For issue 1, the PartiQL functions were indeed ignored in previous releases. I will add them in.
For paging, that is definitely a good idea. I will consider it as a new feature in the next release.

**Comment by passren** [comment] 2023-02-17 01:54
@ohjisu 0.4.6 released to add PartiQL functions support.

Support following PartiQL functions: _begins_with, missing, attribute_type, contains, size_ in SELECT.
**EXISTS** function is not supported due to illegal SQL grammar.

For paging, you are able to use result_set.fetchmany(size) to get data with your page size.

**Comment by ohjisu** [comment] 2023-02-19 23:11
Hi!
Thanks for the quick update.
I will use it after updating to the latest version(0.4.6).

**Comment by ohjisu** [comment] 2023-02-20 23:55
I updated it to version 0.4.6 and tested it.
_begins_with(), contains()_ Neither seems to work.
If the limit is used together, the limit does not work either.

**Comment by passren** [comment] 2023-02-21 07:45
@ohjisu I guess this problem is caused by wrong quotes in the functions. You have to use double-quote to embrace column name and single-quote to embrace value.

F.e.
begins_with("col_str", 'Online')

Please refer to the examples here: [Using the BEGINS_WITH function with PartiQL for DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ql-functions.beginswith.html)

**Comment by passren** [comment] 2023-03-14 09:44
@ohjisu Did this enhancement work for you? Can I close the issue? Looking forward to your feedback.

**Comment by ohjisu** [comment] 2023-03-15 07:43
@passren
Yes, I think it would be good to close the issue.
Thank you.

**Closed** 2023-03-15 13:58 UTC
Labels: enhancement, good first issue
